include:
  - ./monitoring.compose.yaml

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        restart: "always" # Always restart container
        ports:
         - "80:80" # Port mappings in format host:container
         - "443:443"
        networks:
         - nginx-proxy # Name of the etwork these two containers will share
        volumes: # Volumes needed for container to configure proixes and access certificates genereated by Let's Encrypt companion container
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - "nginx-conf:/etc/nginx/conf.d"
         - "nginx-vhost:/etc/nginx/vhost.d"
         - "html:/usr/share/nginx/html"
         - "certs:/etc/nginx/certs"
    acme-companion:
        image: nginxproxy/acme-companion
        restart: always
        container_name: acme-companion
        volumes:
         - "acme:/etc/acme.sh"
         - /var/run/docker.sock:/var/run/docker.sock:ro
         - "nginx-conf:/etc/nginx/conf.d"
         - "nginx-vhost:/etc/nginx/vhost.d"
         - "html:/usr/share/nginx/html"
         - "certs:/etc/nginx/certs"
        volumes_from:
         - nginx-proxy
        env_file: "setup/.env"
        depends_on:
            - nginx-proxy
networks:
    nginx-proxy:
volumes:
    nginx-conf:
    nginx-vhost:
    html:
    certs:
    acme: